#!/bin/bash
cd /home/lsminer/lsminer

CURRENT_ACCESSKEY=$(cat /home/lsminer/lsminer.conf | cut -d ' ' -f 1 | tr '[:upper:]' '[:lower:]' | tr -d '\r' | tr -d '\n')
echo $CURRENT_ACCESSKEY
NEW_ACCESSKEY=''
while [ -z "$NEW_ACCESSKEY"]; do
	NEW_ACCESSKEY=$(DISPLAY=:0 sudo zenity --entry --text="\n\n你必须设置Accesskey使设备和账号进行绑定，登陆后台可以查看Accesskey，或者联系客服。\n"  --title="更改Accesskey" --width=600 --height=220 --entry-text="$CURRENT_ACCESSKEY")
	wait && sleep 1
done

echo "$NEW_ACCESSKEY" | sudo tee /home/lsminer/lsminer.conf > /dev/null 2>&1
DISPLAY=:0 sudo zenity --info --text="\n<b>Accesskey已经成功修改</b>" --ellipsize 

wait && sync && sleep 1

